### ISSUE TITLE
Add support for "type:[...]" as an alternative to "anyOf"

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/swagger2#10]
As discussed over email... whilst trying to work out how to validate 'string OR null' I came across the type: [ "integer", "null" ] syntax.

This did seem to work in your validator upon initial tests.. but then I came to need to validate "string as format date-time OR null'.

I tried:

type: [ "string", "null"],
format: "date-time"

to no avail.

I 'think' the array based type syntax is still meant to be supported in draft 4: http://json-schema.org/latest/json-schema-validation.html#anchor79

However, I've got no idea what the combination of string + format with such a type array should do really.

The suggested syntax for this is now anyOf/oneOf I believe, which is think implemented as expected.

http://stackoverflow.com/questions/22565005/json-schema-validate-a-number-or-null-value

**Comment by jhthorsen** [comment]
Thanks for the issue. I'm not quite sure when I have time to fix this. Let me know if it takes too long.

I will take a pull request for this. @jajm: Anything you want to look at...?

**Comment by jhthorsen** [comment]
I'm a bit surprised myself to see that I've actually implemented this. It's not often that I don't remember the code I've written.

Anyhow...As you can see from the commit above (1fc846a) I fail to reproduce what you're saying. I have also tested this here: https://github.com/jhthorsen/swagger2/blob/master/t/jv-union.t#L11

**Comment by mrenvoize** [comment]
Thanks for looking into this so quickly.. I'll double check my findings, perhaps I was failing somewhere else further down my code outside the schema validator. Hmmm

**Comment by jhthorsen** [comment]
Next time: Make sure you have a small reproducible example.
