### ISSUE TITLE
Is Mojolicious 6 really required ?

### ISSUE THREAD

**Issue by jajm** [jhthorsen/swagger2#14]
Hi,

We're trying to use Swagger2 in [Koha](http://koha-community.org/) and to package it for Debian.
The problem is that Mojolicious 6 in not packaged yet, making things a little harder.
I did some tests with Swagger2 using the latest packaged version of Mojolicious (5.54) and it seems to work.
So, my question is: is it possible for Swagger2 to require Mojo 5.54 instead of 6 ? Is there any feature I could have missed that really require Mojo 6 ?

**Comment by jhthorsen** [comment]
I will try to change the dependency to 5.54.

**Comment by jhthorsen** [comment]
Seems to work very well :+1: 

New version is soon available on CPAN.

**Comment by jajm** [comment]
Thanks! :)
