### ISSUE TITLE
Warning about undefined value when no operationId supplied

### ISSUE THREAD

**Issue by AllanCochrane** [jhthorsen/swagger2#16]
I think https://github.com/jhthorsen/swagger2/blob/master/lib/Mojolicious/Plugin/Swagger2.pm#L242 would be better as

```perl
my $name = decamelize(ucfirst($info->{operationId} || $route_path));
```
The ucfirst() function seems to be binding more tightly than the || operator

**Comment by jhthorsen** [comment]
Thanks. I'll look into it soon.
