### ISSUE TITLE
Validating array type parameters

### ISSUE THREAD

**Issue by AllanCochrane** [jhthorsen/swagger2#17]
Do you have any plans to validate parameters with type array?

**Comment by jhthorsen** [comment]
I'm not sure how that works. Can you point me to some documentation/examples?

**Comment by AllanCochrane** [comment]
Hi,

Take a look at http://petstore.swagger.io/#!/pet/findPetsByTags

which looks like http://editor.swagger.io/#/ (goto line 122 in YAML) Note
that the editor does not create a correct query string, it incorrectly
generates the query ...?tags[]=tag1&tags[]=tag2 (multi format I think) when
it should write tags=tag1,tag2 - the csv format, see
https://github.com/swagger-api/swagger-editor/issues/363

I don't think the online swagger.io tools do input array validation. I
haven't looked at their generated clients though

**Comment by jhthorsen** [comment]
This is interesting, thanks for the link. Will let you know when I have time to investigate further.

**Comment by jhthorsen** [comment]
I hope version 0.46 works as you expect. Please let me know if it doesn't.
