### ISSUE TITLE
Unable to use the same method name as operationId across different controllers(resources)

### ISSUE THREAD

**Issue by kberov** [jhthorsen/swagger2#23]
According to the swagger specification [operationObject](http://swagger.io/specification/#operationObject):
> operationId |string| Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

It should be possible to use methods with identical names in different controllers.
For example: Controller1::list, Controller2::list. They finally end up as different resources(routes) i.e. /controller1/list, controller2/list.
The notation for an operationId in the .yaml/.json can be either changed to ```"operationId": "Controller:list"```. This way we will even completely strictly abide to the Swagger2 specification.
Or left like now: 
```
"x-mojo-controller": "Controller1"
operationId: "list"

// later in the same or another api file
"x-mojo-controller": "Controller2"
operationId: "list"

```
The ```operationId``` is still unique since it resides in different namespace even according to Swagger2.

I think either the used route naming algorithm should be changed or left to Mojo or the uniqness check should be changed.
Currently I get the following error when I have methods with the same name in different routes:

Can't load application from file "/home/berov/appname": list is not a unique route! (get /exusers) at /home/berov/perl5/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Mojolicious/Plugin/Swagger2.pm line 343

Regards and thanks for the good work!

**Comment by jhthorsen** [comment]
I totally agree. I think I will see what happens if I include the controller in the route ```name()```. I might also remove it completely as suggested.

**Comment by kberov** [comment]
Thanks!
