### ISSUE TITLE
Swagger2::Editor ace editor component documentation

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/swagger2#32]
It's not clear how to use the /editor functions of Swagger2::Editor.

When attempting to clone the repo and run up the blog demo, the /editor route is missing ace.js dependency.

**Comment by mrenvoize** [comment]
To get the editor to work, I had to add the following files to t/blog/public/

ace.js  mode-json.js  theme-solarized_dark.js  worker-json.js

all grabbed from the ace builds repo: https://github.com/ajaxorg/ace-builds/

**Comment by mrenvoize** [comment]
I actually like that they're not included here.. though perhaps the Swagger2::Editor package could use a CDN link?

**Comment by jhthorsen** [comment]
Sure you're not just missing / after /editor/ ? I haven't worked out that bit yet :disappointed:

**Comment by mrenvoize** [comment]
Oh wow.. adding the trailing / does make the difference..  I have no idea why.. but indeed it does get it working.  Thanks

**Comment by jhthorsen** [comment]
Closing this, based on the feedback.
