### ISSUE TITLE
$ref support and multi-file specifications

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/swagger2#33]
I was hoping to create a structure something along the lines described [here](http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html)

But this seems to be incompatible with the current implementation of the mojo plugin structure.. any thoughts on how to achieve similar with this swagger implementation?

**Comment by jhthorsen** [comment]
You need to show code or even better create a failing test. I don't understand what doesn't work. $ref is indeed supported and there are multiple tests for it. I might have bugs, but I don't understand what that is without further information.

**Comment by mrenvoize** [comment]
A test app based upon your Blog demo: https://github.com/mrenvoize/swagger-test..

Try running:

script/blog routes

You'll see the linked files are not picked up..

**Comment by jhthorsen** [comment]
So the issue is "Support for $ref to relative locations/file/url" ?

**Comment by mrenvoize** [comment]
pretty much.. sorry, I suppose most of the chatter went on on irc.. I should have cloned it here

**Comment by mrenvoize** [comment]
I suppose a 'spec' is in order.

I see the following scenarios for $ref usage.

private spec files
as in the example, a spec file and associated definitions files within the app but not publicly served

public spec files
as in example, but perhaps under the /templates or /public directories and thus served by mojolicious server when run up (with either full or relative urls in the refs themselves created via a template process perhaps?)

Does that make sense?

**Comment by jhthorsen** [comment]
I need a proper spec. I'm not sure if I read the spec correct, but I don't think there's anything against this functionality. On the other hand, this is not something I want to jump into before I fully understand it or see other implementations that does the same thing.

http://json-schema.org/latest/json-schema-core.html#anchor30

**Comment by mrenvoize** [comment]
This issue was moved to jhthorsen/json-validator#4
