### ISSUE TITLE
x-mojo-controller vs operationId

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/swagger2#36]
At the moment we require both x-mojo-controller and operationId to construct a handler for a route.

With swagger 2.0 requiring operationId to be unique across the entire specification, then we could in actual fact do away with x-mojo-controller all together.

Optionally doing this may be the way forward as per irc chat:

**Comment by mrenvoize** [comment]
Just looking at examples across the web and a few things come to mind.

a) It doesn't look like there any particular validation on oeprationId outside of it being a string.  Thus 'App::Controller::Foo::bar' would actually be valid, if a little odd looking compared to other schema.

b) Though CamelCase is used in the examples on the Swagger site itself,that's not necessarily the case elsewhere.

c) The most popular format in my brief bit of research came down to:

> methodControllerOptions

The 'Options' bit is where I get a bit lost.. ById, WithForm (and personally dislike..)  else I'd say there are some reasonably clear rules for converting the string to a controller name + method.

Would welcome others input at this point.

**Comment by jhthorsen** [comment]
I really like c), so i went on and implemented it, with very much the same logic as in #37.

What do you think?

I also decided to _not_ document the "x-mojo-controller" part any more, since I think it should be avoided. I have not deprecated support for it though. I think that is way to early to do.

**Comment by jhthorsen** [comment]
What about ```"operationId": "messagesForConversation"```? Could we resolve that to "messages" method in "Conversation" controller? Or is it simply just a bad operationId?

**Comment by jhthorsen** [comment]
Note that a7f8fa6 is just a suggestion. Not sure if it's a good idea.

**Comment by mrenvoize** [comment]
I think it' an excellent move to remove the documentation for x-mojo-controller.. a step towards deprecating it perhaps :)

The 'Options' bit was always the hardest bit to work out how to generalize here.. i.e. the By/For/Of/To stuff, but I in general think your approach is good.

Also worth noting is the de-pluralisation that's going on.. i.e getUser and getUsers both resolve to the same 'get' method in the 'User' controller.. which I also totally agree with :)

**Comment by jhthorsen** [comment]
Fixed in 0.58.

**Comment by tyldum** [comment]
I vote to keep x-mojo-controller around as a possibility to override the controller derived from operationId.
If the client and server share the Swagger2 spec and both tie into operationId then the spec must be changed to accommodate internal changes on either side and then the actual code must reflect that.

By keeping x-mojo-controller we can still use the same spec, just do a quick transformation of it if necessary.
