### ISSUE TITLE
Fails on windows

### ISSUE THREAD

**Issue by andk** [jhthorsen/swagger2#4]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/bd54f97b-7e00-1014-8144-e0ed229b6c94

Bugline for the editor.t failing:

https://metacpan.org/source/JHTHORSEN/Swagger2-0.15/lib/Swagger2.pm#L63

The join "/" apparently needs to be replaced with a catfile.

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by jhthorsen** [comment]
I don't understand how that can be correct:

    Could not load document from c:/Smoker/5201x86/cpan/build/Swagger2-0.15-Wnza08/blib/lib/Swagger2/schema.json#: Missing or empty input

The path above looks like a windows filename to me..?

Also, ```catfile``` should not be used at that line, since it gets converted into a Mojo::URL object, and the catfile is used after it has been split on "/".

I think I will simply disable the whole test ```if $^O eq 'Win32'```

**Comment by jhthorsen** [comment]
Ah! I think it fails when converted into Mojo::URL. "c:/" is probably the beginning of the URL, so $scheme turns will be "c", instead of "file".

**Comment by andk** [comment]
>>>>> On Fri, 02 Jan 2015 03:24:45 -0800, Jan Henning Thorsen <notifications@github.com> said:

  > I don't understand how that can be correct:
  > Could not load document from c:/Smoker/5201x86/cpan/build/Swagger2-0.15-Wnza08/blib/lib/Swagger2/schema.json#: Missing or empty input

  > The path above looks like a windows filename to me..?

  > Also, catfile should not be used at that line, since it gets converted into a
  > Mojo::URL object, and the catfile is used after it has been split on
  > "/".

Are we looking at the same line? I see this:

   join '/', File::Spec->splitdir(File::Basename::dirname(__FILE__)), 'Swagger2', 'schema.json';

There is no split on "/", there is a splitdir; on windows that would
normally be a split on "\\" and it would deal correctly with the drive
identifier "c:" and all that funky stuff.

  > I think I will simply disable the whole test if $^O eq 'Win32'

That would be a pity, imho. Even though, thanks god, I do not work with windows:)

-- 
andreas

**Comment by jhthorsen** [comment]
Yes, we are looking at the same file. The Mojo::URL part is here: https://github.com/jhthorsen/swagger2/blob/master/lib/Swagger2.pm#L130

**Comment by jhthorsen** [comment]
I _hope_ this will fix it.

**Comment by jhthorsen** [comment]
Thank you!

I will have a look at cpan testers result now that I'm back from vacationss

**Comment by jhthorsen** [comment]
Still doesn't work right. I wonder if I can emulate Windows somehow...

**Comment by jhthorsen** [comment]
I forget to reference this issue in my commits. Made a new release to CPAN now:

https://github.com/jhthorsen/swagger2/commit/74e45ac8d548d62322e0d6fd3b98abc1d55f4f48

**Comment by andk** [comment]
>>>>> On Sat, 03 Jan 2015 01:25:10 -0800, Jan Henning Thorsen <notifications@github.com> said:

  > Still doesn't work right. I wonder if I can emulate Windows somehow...

I have activated a Windows system here and had lots of fun with it. This
is a tested patch on top of 0.17.

--- lib/Mojolicious/Command/swagger2.pm	Fri Dec 19 12:26:19 2014
+++ ../Swagger2-0.17-nJZpzh/lib/Mojolicious/Command/swagger2.pm	Sat Jan  3 14:24:25 2015
@@ -145,7 +145,9 @@
 
   if ($ENV{SWAGGER_API_FILE}) {
     $app->defaults(raw => Mojo::Util::slurp($ENV{SWAGGER_API_FILE}));
-    $swagger->load($ENV{SWAGGER_API_FILE});
+    my $api_url  = Mojo::URL->new;
+    $api_url->path->parts([File::Spec->splitdir($ENV{SWAGGER_API_FILE})]);
+    $swagger->load($api_url);
   }
 
   $app->routes->get(


Feel free to reject and find a solution you like more. I'm glad if I
helped you to get to an interesting spot.

-- 
andreas

**Comment by andk** [comment]
I don't have my best day today. I sent the above comment as mail and then tried to edit it to look better and it got worse and worse. I'll keep my hands off now...

**Comment by jhthorsen** [comment]
@andk: Can you test the git repo? That way, I don't have to install to cpan before you test my latest commit.

**Comment by andk** [comment]
>>>>> On Sat, 03 Jan 2015 06:40:47 -0800, Jan Henning Thorsen <notifications@github.com> said:

  > @andk: Can you test the git repo? That way, I don't have to install to cpan
  > before you test my latest commit.

All tests pass on my Strawberry perl 5.20.1 with 0475db52

Congrats,
-- 
andreas

**Comment by jhthorsen** [comment]
Awesome! Thank you :smile:
