### ISSUE TITLE
Upgrade dependency on Mojo::JSON::Pointer

### ISSUE THREAD

**Issue by dolmen** [jhthorsen/swagger2#43]
I just submitted a fix for Mojo::JSON::Pointer: kraih/mojo#851
Once it is merged it would be important to upgrade the dependency of Swagger2 on Mojo::JSON::Pointer.

**Comment by jhthorsen** [comment]
I guess you mean you want me to bump the Mojolicious version dependency here? https://github.com/jhthorsen/swagger2/blob/master/cpanfile#L3

If so, I can't do this at the time being because I have other dependencies I have to upgrade first.

Let me know if I misunderstood.
