### ISSUE TITLE
YAML (not ::XS) parser fails to handle non-inline parameter definitions

### ISSUE THREAD

**Issue by denny** [jhthorsen/swagger2#50]
As per discussion on IRC...

M::P::S using the YAML module to parse a valid swagger file, will explode like so:
https://ssl.thorsen.pm/paste/ec3ff986b44d

... but it works okay with YAML::XS

This might be worth adding to a Known Issues section in the docs (along with the boolean thing?) to help anyone else who trips over it figure out what the problem is.

**Comment by jhthorsen** [comment]
In case i delete the paste: The line in question is:

    - $ref: '#/parameters/appname'

JSON.pm will interpret that as a string, while it's really an object. The fix is:

    - { '$ref': '#/parameters/appname' }

After some more consideration, I think I will change the module to require JSON::XS, since JSON also lack logic to handle booleans.
