### ISSUE TITLE
Add 'From' to list of ignored words in SKIP_OP_RE

### ISSUE THREAD

**Issue by dboehmer** [jhthorsen/swagger2#54]
We have a `delete` controller method and I'd prefer to use the `operationId` `deleteFromFoobar`.

To do some CRUD or REST one could name the controller methods like this:
* C: `createFoo` or `createInFoos`
* R: `getFoo` or `getFromFoos`
* U: `updateFoo` or `updateInFoos`
* D: `deleteFoo` or `deleteFromFoos`

I think `From` is the only word missing in order to have nice method names for all action types.

**Comment by jhthorsen** [comment]
Thank you! I like it :+1:
