### ISSUE TITLE
boolean headers

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/swagger2#58]
Another note to get it down whilst I remember it, one for me to review over xmas.

At the moment, a header can take the type 'boolean', which must be passed a boolean object to validate.. but what comes out the other end in the actual http header is bare '0/1'.. I "think" these should be bare 'true/false' in line with json.

**Comment by jhthorsen** [comment]
Do you mean that $args->{x_header} contains 1 and 0 inside the controller method?

**Comment by mrenvoize** [comment]
13:24 <batman> ashimema: that's because the objects stringify as 1 or 0. Can't do much about that :/
13:25 <batman> Hm... Wait a sec.
13:25 <ashimema> I thought they stringified to a bare 'true/false'
13:26 <batman> No. The string "false" is true in Perl :)
13:26 <ashimema> but come to think of it... I'm likely thinking of json objects
13:26 <ashimema> indeed
13:26 <batman> So it has to stringify to "" or 0
13:26 <ashimema> it's { "key": true } i'm thinking of
13:27 <ashimema> as this is a bare value, outside of a json obj then it's not the case :(
13:27 <batman> But maybe (note "maybe") swagger need to convert 1/0 into true/false in the headers.
13:27 <ashimema> hmm
13:27 <batman> But please show a client that fails with 0/1 first.
13:27 <ashimema> hmm
13:28 <ashimema> well our client does..
13:28 <ashimema> but that's of course because we wrote it ;)
13:28 <ashimema> for hwo the behaviour was and how I expected it to be..
13:29 <batman> Hehe. Well... We could stringify to true/false in the headers.
13:29 <batman> Don't see anything wrong with that...
13:29 <ashimema> to be fair.. I can't find anything anywhere that talks about what they 'should' be
13:30 <batman> Though 1/0 is easier for me (coming from Perl) it might be just as difficult as true/false in js world
13:30 <ashimema> but for us. it felt more consistent to be the bare strings.. as that's what we have in all our json eveywhere..
13:30 <ashimema> well.. we likely had to write out own parser to 'mean' true/false anyway ;)
13:30 <batman> Sure. Sorry, can't hack on this now, but go crazy if you want
13:30  * ashimema ponders
13:31 <ashimema> true/false 'feels' clearer to me..
13:31 <batman> I don't think I will revert it.
13:31 <batman> +1
13:31  * ashimema has always found perls lack of booleans a bit strange ;)
13:31 <batman> It sounds like a Boolean value
13:31 <ashimema> K.. I may have a quick hack ;)
13:31 <batman> 1/0 looks like a number

**Comment by mrenvoize** [comment]
Fantastic, thanks for this.. looks like you've had a busy few hours of coding upon the return from your hols.

**Comment by jhthorsen** [comment]
Hehe, Yeah. It was fun hacking again :+1:
