### ISSUE TITLE
Support x-nullable (or x-isnullable) extension ?

### ISSUE THREAD

**Issue by le-garff-yoann** [jhthorsen/swagger2#59]
Hello,

Is it possible to support `x-nullable` (or `x-isnullable`) extension (to bypass this: https://github.com/swagger-api/swagger-spec/issues/229) ?

By the way, thank you for your work :)

**Comment by jhthorsen** [comment]
I'm afraid I don't follow. (Even tried to read swagger-spec#229).

Can you give me a full example on which input and/or output that doesn't work? Or even better: Write a test like i did in d478c76.

**Comment by le-garff-yoann** [comment]
I will test what you did in d478c76.

Thanks for your reactivity ! :)

**Comment by le-garff-yoann** [comment]
It's OK for me. Thank you for your help.

**Comment by jhthorsen** [comment]
:+1:
