### ISSUE TITLE
Debug output from Mojolicious::Plugin::Swagger2 is missing basePath prefix

### ISSUE THREAD

**Issue by dboehmer** [jhthorsen/swagger2#64]
I've spent quite some time debugging why my callbacks wouldn't be fired although the debug output perfectly showed that the paths were parsed and the routes were created correctly … :-(

I just found out that the debug output is missing the prefix defined in the Swagger file. Could you please add that to the message `[Swagger2] Add route get /foo` like `[Swagger2] Add route get /v1/foo`.

The debug output from the Mojolicious app is not correctly reflecting what is actually happening in the Mojolicious app. I tried to dig into that module but just don't understand how the basePath is actually included in the route paths.

**Comment by jhthorsen** [comment]
Oh. That's no good.

Could you see if 5feaf68 fixes the issue?

**Comment by dboehmer** [comment]
Yes, the issue is fixed. Thank you for your quick fix!
