### ISSUE TITLE
Deprecate swagger_route_added hook

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/swagger2#65]
I want to deprecate the ```swagger_route_added``` hook in favour of the ```before_generate_request_handler``` suggested in #55. (Note: "before_generate_request_handler" should probably be called something else)

```swagger_route_added``` was added to be able to customise the name of the route. This could be done inside ```before_generate_request_handler``` handler instead.

Suggested API:

```
$before_generate_request_handler->($defaults, $route);
```

The reason for this change is simply to remove _on_route_added().

Going to leave this open to see if anyone objects.

**Comment by jhthorsen** [comment]
Closing this in favour of https://github.com/jhthorsen/mojolicious-plugin-openapi

**Comment by srchulo** [comment]
Is there a reason to not use the backwards compatible method for this listed here?

https://metacpan.org/pod/distribution/Mojolicious-Plugin-OpenAPI/lib/Mojolicious/Plugin/OpenAPI/Guides/Swagger2.pod

It seems nice to not have to call 

`my $self = shift->openapi->valid_input or return;`

At the beginning of each OpenApi method.

**Comment by jhthorsen** [comment]
Yes. It's really annoying to get around it if you have the same action for both OpenAPI and other things. 

Also, it's not the standard way for actions to behave in the "Mojolicious World", which makes it harder for new people to read your code.

**Comment by srchulo** [comment]
So I only have these actions used for OpenAPI. In this case you're saying it would be okay (except for the harder to read part)?

Also, is this not possible to do with under? That would be more Mojolicious-esque, but I guess that would only be on the way into the action and not on the way out.

If the recommended way is now to do it in the action itself, I guess I will just do that for consistency.

**Comment by jhthorsen** [comment]
I'm saying I like `shift->openapi->valid_input or return`, but you can do what you want.

under() would not be the same, since it does not pass arguments into the action.

**Comment by srchulo** [comment]
Got it, thanks! I'll just continue using `shift->openapi->valid_input or return`.
