### ISSUE TITLE
anyOf not supported by POD generator ?

### ISSUE THREAD

**Issue by jajm** [jhthorsen/swagger2#7]
Hi,

I just discovered Swagger this week, and it's fantastic! But I have a problem generating POD with the following YAML file:

    ---
    swagger: 2.0
    paths:
      /foo:
        get:
          responses:
            200:
              description: A foo
              schema:
                type: object
                properties:
                  identifier:
                    description: Identifier
                    anyOf:
                      - type: integer
                      - type: string

When I run `mojo swagger2 perldoc test.yaml`, I get an error:

    Not a HASH reference at /usr/local/share/perl/5.14.2/Swagger2/POD.pm line 245.

Looking at the Swagger2::POD code, it seems that anyOf, allOf, and oneOf are not supported.
When I replace the anyOf part with `type: integer` it works well.

Am I missing something ?

**Comment by jhthorsen** [comment]
Unfortunately, I don't think you're missing anything.

I will look into it.

**Comment by jhthorsen** [comment]
Oh! I actually have no idea how to display that in pod... Can you give me input on how you think it should be formatted?

**Comment by jajm** [comment]
I don't know how to display that either. But here is my attempt to fix the problem: https://github.com/jajm/swagger2/commit/1391f8f2d5bf9a996d6aa2d8bf9fe45c7a30aabc
I hope this will help.

**Comment by jhthorsen** [comment]
Thanks for the example code! :+1: 

I will make a new release soon (0.29) with a modified version of your suggestion. Let's iterate on that, in case you don't like it.
