### ISSUE TITLE
Fix spelling error in manpage

### ISSUE THREAD

**Issue by lucaskanashiro** [jhthorsen/swagger2#70]
In Debian we are currently applying the following patch to Swagger2.
We thought you might be interested in it too.

    Description: fix spelling error in manpage
    Author: Lucas Kanashiro <kanashiro.duarte@gmail.com>
    Last-Updated: 2016-02-02
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libswagger2-perl.git/plain/debian/patches/fix-spelling-error-in-manpage.patch

Thanks for considering,
  Lucas Kanashiro,
  Debian Perl Group

**Comment by gregoa** [comment]
The same typo appears a second time; updated patch at the above location.

Cheers,
gregor

**Comment by jhthorsen** [comment]
Thank you :+1:

**Comment by jhthorsen** [comment]
Btw: Do you want me to make another release now, or can I wait?

**Comment by gregoa** [comment]
Thanks to you :)
There's no need for a release from our point of view, as we are shipping the version with the patch anyway.

**Comment by jhthorsen** [comment]
Cool! Thank you :smile:
