### ISSUE TITLE
Swagger2::Client: not taking path params equals to 0

### ISSUE THREAD

**Issue by le-garff-yoann** [jhthorsen/swagger2#74]
Hello,

In my Swagger2 spec, I have:
- an *operationId* with one path parameter of type string.

But (when used with `Swagger2::Client`) the parameter is not set (or set to `''`) when i pass a value equal to 0 (or "0") to the generated method:

- expected
```
http://127.0.0.1/a/0/b
```

- got
```
http://127.0.0.1/a//b
```

According to my tests, the problem comes from:

`Swagger2::Client` line 69: `||''`

```perl
push @{$req->[0]->path->parts}, map { local $_ = $_; s/\{(\w+)\}/{$args->{$1}||''}/ge; $_; } @path;
```

**Comment by jhthorsen** [comment]
Thank you :+1: 

Will make a new release soon.
