### ISSUE TITLE
Resolving JSON references fail, if the referenced file has 'id' as a root attribute.

### ISSUE THREAD

**Issue by kivilahtio** [jhthorsen/swagger2#75]
When trying to load the swagger/test.json from the example test set, I get the following error:

Could not load document from ../../test/defs.json: Can't open file "../../test/defs.json": No such file or directory at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 407.
 () at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 414, <DATA> line 2125.

This is because of a 'id'-attribute in the root of a referenced .json-file.

I have the following directory structure

swagger/test.json
swagger/test/paths.json
swagger/test/path/fail.json

File contents as follow:
**swagger/test.json**
{
  "swagger": "2.0",
  "basePath": "/api/v1",
  "info": {
    "license": {
      "url": "http:\/\/www.gnu.org\/licenses\/gpl.txt",
      "name": "GPL v3"
    },
    "contact": {
      "url": "http:\/\/koha-community.org\/",
      "name": "Koha Team"
    },
    "title": "Koha REST API",
    "version": "1"
  },
  "definitions": {
    "$ref": "test/paths.json"
  },
  "paths": {
  },
  "parameters": {
  }
}

**swagger/test/paths.json**
{
    "$ref": "test/path/fail.json"
}

**swagger/test/path/fail.json**
{
    "id": "THIS BREAKS THE PARTY!",
    "description": "desc"
}

**Comment by kivilahtio** [comment]
Maybe a good solution is to add this:

  die "[JSON::Validator] File $namespace contains an abnormal 'id'. Are you sure you haven't manually defined 'id' in that file?\n"
       if(ref($doc->data->{id})); #If the id is something else than scalar, die

to this:

JSON::Validator::
sub _register_document {
  my ($self, $doc, $namespace) = @_;

  $doc = Mojo::JSON::Pointer->new($doc);
  $namespace = Mojo::URL->new($namespace) unless ref $namespace;
  $namespace->fragment(undef);

  $self->{cached}{$namespace} = $doc;
  $doc->data->{id} ||= "$namespace";
  $self->{cached}{$doc->data->{id}} = $doc;

  die "[JSON::Validator] File $namespace contains an abnormal 'id'. Are you sure you haven't manually defined 'id' in that file?\n"
       if(ref($doc->data->{id})); #If the id is something else than scalar, die

  warn "[JSON::Validator] Register id=$doc->{data}{id} namespace=$namespace\n" if DEBUG;
  return $doc;
}

**Comment by jhthorsen** [comment]
This doesn't make much sense.

Clone the repo. Make a failing test. And don't make up cases.

**Comment by kivilahtio** [comment]
Hi!
Just updated the example scenario. This will ruin your day :)

**Comment by kivilahtio** [comment]
Here is a test which replicates this issue.
https://github.com/KohaSuomi/swagger2/commit/b21232ed1c6e901f25e56206054565abd4a63600
