### ISSUE TITLE
response type of ` Mojolicious::Plugin::Swagger2::render_swagger`

### ISSUE THREAD

**Issue by SmartHoneybee** [jhthorsen/swagger2#78]
How do I use `Mojolicious::Plugin::Swagger2::render_swagger` properly to get a response of a different type than the default `application/json`?

I would like to return `application/xml` iff the client requested it and `application/json` otherwise. If I understand correctly I could just use `Mojolicious::Controller::respond_to` to render a response but would then lose the parsing and validation of the response.

Can I have both a custom type and a valid response?

Thank you.

**Comment by jhthorsen** [comment]
I don't really know, but the idea is something like this:

```
# Override the helper
$app->helper(render_swagger => sub {
  my ($c, $err, $data, $status) = @_;
  my $format = $c->stash('format') || 'json'; # default to json or xml

  # $format is set based on things such as "URL extension":
  # http://api.example.com/foo.xml ==> $format = "xml"
  if ($format eq 'xml') {

    # You need some common error template with faultstring/faultcode and friends
    return $c->render('some_xml_error_template' => {fault => $err}, status => $status) if %$err;

    # If you have data, render a template relative to the current request
    return $c->render(xml_data => $data, status => $status) if ref $data;

    # $data might be just be a string you should render as data
    return $c->render(data => $data, status => $status);
  }
  else {
    # This is copy/paste from the original render_swagger() helper
    return $c->render(json => $err, status => $status) if %$err;
    return $c->render(ref $data ? (json => $data) : (data => $data), status => $status);
  }
});
```

You could probably use a CPAN library for generating the XML document instead of using a template, but  be aware of bad XML modules, with issues such as order of document nodes - if that matters.

Please report back if you have further questions. I would very much appreciate a documentation pull request if you make it work. (Doesn't have to be complete)

Also, questions like these can be asked in the #swagger channel on irc.perl.org.

**Comment by SmartHoneybee** [comment]
(No futher questions, just some feedback.)

Overriding the helper did the trick, thanks!
Using the [Working with helpers](https://github.com/kraih/mojo/wiki/Working-with-helpers) page I ended up with something like this:
```perl
package Awesome;
use Mojo::Base 'Mojolicious';

sub startup {
  my $app = shift;
  $app->plugin(Swagger2 => {
      url => 'swagger.yaml',
    });
  $app->plugin('Awesome::Helper');
}
1;
```
with this `Awesome::Helper` plugin overriding `render_swagger`:
```perl
package Awesome::Helper;
use Mojo::Base 'Mojolicious::Plugin';

sub toXML {
  # magic
}

sub register {
  my ($self, $app) = @_;
  delete $app->renderer->helpers->{render_swagger};
  $app->helper(
    render_swagger  => sub {
      my ($controller, $err, $data, $status) = @_;
      $data = $err if %$err;
      return $controller->respond_to(
        xml => {
          text   => toXML($data),
          status => $status,
        },
        any => {
          ref $data ? (json => $data) : (data => $data),
          status => $status,
        },
      );
    }
  );
}
1;
```

**Comment by jhthorsen** [comment]
Glad it worked out!

Btw: You don't have to delete the old helper before adding a new.
