### ISSUE TITLE
Support mocking of API endpoints (response data)

### ISSUE THREAD

**Issue by leejo** [jhthorsen/swagger2#82]
My approach to working with RESTful APIs is to write an emulator for whatever API i am coding against. It gives me better test coverage and speeds up the development. Actually this is the subject of a short talk i'll be giving at YAPC: https://github.com/leejo/emulation_driven_development/blob/master/presentation.md

Anyway, if you're using Swagger2 then it should be a piece of cake to do this:

```
# setup API routes from swagger config
plugin Swagger2 => {
    route => $api,
    url   => "https://za.payprop.com/api/docs/swagger.yaml",
    mock_endpoints => 1,
};
```

In the case of `mock_endpoints` being set, when the plugin fails to find the listed `x-mojo-controller` and `operationId` it just logs and returns (one of) the example response data structures. Suddenly you have an emulator for your entire API from 5 lines of code. Awesome!

I'm currently looking at this but being distracted by other things so don't know when i'll get around to completing it.

**Comment by leejo** [comment]
So for example in the case of t/data/petstore.json we have (non-relevant keys removed):

```json
    "/pets": {
      "get": {
        "x-mojo-controller": "t::Api",
        "operationId": "listPets",
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/Pet" }
            }
          }
        }
      },
```

If the plugin can't find `t::Api::listPets` and `mock_endpoints` is set then we just grab the `200` response struct and return that. It's defined as:

```json
    "Pet": {
      "required": [ "id", "name" ],
      "properties": {
        "id": { "type": "integer", "format": "int64" },
        "name": { "type": "string" },
        "tag": { "type": "string" }
      }
    }
```

So we're going to return a 200 OK with:

```json
[
  {
    "id" : 1,
    "name" : "pooch"
  }
]
```

I guess if the schema definitions lack `x-example` data then we will have to generate random info for those values?

We may also want to set an `X-` header to make it clear that response data was mocked if this functionality is used for stub methods in a live API.

**Comment by jhthorsen** [comment]
Please re-open this ticket for https://github.com/jhthorsen/mojolicious-plugin-openapi

I will slowly abandon this namespace in favour of "OpenAPI".
