### ISSUE TITLE
formData parameters not being handled correctly in Swagger2::Client

### ISSUE THREAD

**Issue by huntsberg** [jhthorsen/swagger2#85]
I found an issue with validation of formData parameters in the Swagger2::Client module.  It looks like a schema is expected for formData parameters, but it looks like the schema is only required for 'in body' parameters.

I also found an issue where the form was being set to the last value instead of being created as a hash of the name value pairs. 

I'll include a pull request

**Comment by huntsberg** [comment]
See Pull Request #86

**Comment by jhthorsen** [comment]
Closed by #87.

Thank you for your contribution 👍
