### ISSUE TITLE
$ref a whole Paths-, Definitions-, Parameters-, Info-objects in root document.

### ISSUE THREAD

**Issue by taskula** [jhthorsen/swagger2#89]
Hello. I have a question about validating $ref. I want to split my Swagger specification over multiple files. By referencing a whole Definitions-object (or Paths, Parameters, Info-objects) to another file like in following example, **works well** with `mojo swagger2 validate`: 
```
{
  "swagger": "2.0",
  "info": {
    "$ref": "info.json"
  },
  "paths": {
    "$ref": "paths.json"
  },
  "parameters": {
    "$ref": "parameters.json"
   },
  "definitions": {
    "$ref": "definitions.json"
  }
}
```
Thats great, but my question comes from https://github.com/swagger-api/swagger-ui/issues/1878#issuecomment-172138560 which says this
```
"definitions": {
  "$ref": "definitions.json"
}
```
 is not supported. I am a bit confused now, as this type of setup validates with `mojo swagger2 validate`, but not with e.g. online.swagger.io validator. Shouldn't it also fail in `mojo swagger2 validate`? Is this intentionally supported in this  plugin's validation?

**Comment by jhthorsen** [comment]
Oh. That's awful :( Wonder why they decided to resolve $ref differently from JSON-Schema...

Anyway, I'll try to find time to look at this next week.

**Comment by mrenvoize** [comment]
Allot of the $ref handling was requested by me.  I used a number of guides to narrow down on the 'works well' solution. At the time, that was the recommended approach, I'll see if I can dig out that recommendation.

I can't believe the 'swagger people' have now decided that approach should be 'banned'. That's non-nonsensical :(.

**Comment by bensinober** [comment]
But wouldn't that be a swagger-ui bug rather? The json refs spec draft is rather to the point: http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03

So you have anchors (#) for local refs, relative refs, and URI/path refs.

nodejs json-refs has supported this for years: http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html. I can not understand the perl implementation should do otherwise.

**Comment by jhthorsen** [comment]
Yeah, I'm starting to think the same... How can it not be valid, when the spec validates? I mean, if you accidentally add and invalid key somewhere in the spec, then ```mojo swagger2 validate``` will let you know.

@bensinober++

**Comment by mrenvoize** [comment]
@bensinober++ That's the exact article I was looking for to reference :)

I totally agree it's a bug with the Swagger Specification and not our implementation.  There are a few other $ref related areas that annoy me with swagger along these same lines.  For instance, I'm sure I read somewhere that only the /definitions block may be ref'd.. and nothing else is allowed.. what madness is that all about.

**Comment by jhthorsen** [comment]
Note that the test above (ab22d2e) uses https://raw.githubusercontent.com/OAI/OpenAPI-Specification/19fed9f0f812ccebe0fc45313fea75bb6656de1c/schemas/v2.0/schema.json (latest version of the spec)

**Comment by jhthorsen** [comment]
I'm closing this issue unless someone can come up with a failing test. It has happened before that swagger-ui is behind JSON::Validator and Swagger2.

**Comment by jhthorsen** [comment]
This is fixed in Mojolicious::Plugin::OpenAPI. I'm not going to fix it in M::P::Swagger2.
