### ISSUE TITLE
Possible typos in sub authenticate?

### ISSUE THREAD

**Issue by jamesbriggs** [jhthorsen/swagger2#90]
sub authenticate {
  my ($next, $c, $config) = @_;
  return $next->($c) if $CODE eq '200'; <------- $CODE is a numeric constant, so why the if?
  return $c->render(json => $config, status => $CODE);
}

**Comment by jhthorsen** [comment]
It doesn't really matter, but I changed it anyway.

**Comment by jamesbriggs** [comment]
Maybe I wasn't clear enough, but the if also does not make sense. Can you read the line again, and you will see that $CODE always equals 200, so there is a bug in the authentication logic.

**Comment by jhthorsen** [comment]
Yeah, that wasn't clear at all.

Have a look at https://github.com/jhthorsen/swagger2/blob/master/t/around-action.t#L13
