### ISSUE TITLE
Custom error responses

### ISSUE THREAD

**Issue by anschwa** [jhthorsen/swagger2#91]
Hi, how would I be able to define my own `@errors` response JSON so that it matches what I have defined in my `swagger.yaml` document?

Is this possible with your plugin?
Thanks.

**Comment by wfwheele** [comment]
I am also looking for this functionality, but it doesn't seem to be implemented.  Though, it is possible to use the x-mojo-around-action to implement this, but then you also have to implement the validation as well.

**Comment by jhthorsen** [comment]
I suggest looking at Mojolicious::Plugin::OpenAPI. It's the successor for Swagger2. You can do this out of the box with that plugin, since there's no "magical" wrapping of the controller code.

**Comment by jhthorsen** [comment]
Not sure why this issue was closed, but I hope it's because both of you found M::P::OpenAPI useful.

**Comment by anschwa** [comment]
I closed this because that seemed to be the answer. I did try using `OpenAPI` but found `Swagger2` to work better for my use case. Thanks.

**Comment by jhthorsen** [comment]
@anschwa: Why is Swagger2 better than M::P::OpenAPI?

**Comment by anschwa** [comment]
I felt that it was more complete "out of the box". This was my first exposure to `perl` and I found with `M::P::OpenAPI` it did not do validation of input (as defined in the swagger spec) automatically. It was also more confusing which methods I needed / should be using to receive and deliver requests. `$c->openapi->valid_input'` was also resulting in a `500 Internal Server Error`. I imagine most of my difficulties come from never using `perl` or `mojolicious` before.

**Comment by jhthorsen** [comment]
@anschwa: Oh. I'm very sorry to hear that. Could you tell me how the tutorial and/or the SYNOPSIS can be more clear? Would it help if the SYNOPSIS had a "full app" example instead of the ::Lite app?

**Comment by anschwa** [comment]
I actually like the `::Lite` app example and enjoyed working with `::OpenAPI`. I think looking at your tests is helpful and maybe adding your `blog` example from `::Swagger2` would be helpful as well. Again, using your plugins was the first time I've ever written perl at all.

**Comment by jhthorsen** [comment]
OK. Any feedback is more than welcome. Having great documentation, which makes the module easy to work with is very important.
