### ISSUE TITLE
Return property from swagger api_spec

### ISSUE THREAD

**Issue by anschwa** [jhthorsen/swagger2#92]
Hello, 
I was curious if it was possible to return a specific property from the swagger `api_spec` hash object. For example the version number or the base path would be quite helpful.

I imagine something like the following is possible but I'm unsure how to do it.
`my $bp = $c->stash('swagger')->{basePath};`

Thanks.

**Comment by jhthorsen** [comment]
Try this: $c->stash('swagger')->api_spec-get("/basePath")

Please ask questions in the #swagger channel on irc.perl.org. GitHub is not a place to ask questions.

**Comment by anschwa** [comment]
That works great, thanks.
