### ISSUE TITLE
api.json missing several properties

### ISSUE THREAD

**Issue by jamesbriggs** [jhthorsen/swagger2#94]
1) petstore spec file should be updated to start like this:

{
  "swagger": "2.0",
  "info": {
    "title": "Swagger Petstore",
    "description": "Swagger Petstore",
    "license": {
      "name": "Artistic License version 2.0",
      "url": "http://dev.perl.org/licenses/artistic.html"
    },
    "termsOfService": "http://www.example.com/terms",
    "contact": {
       "name": "API Support",
       "url": "http://www.example.com/support",
       "email": "support@example.com"
    },
    "version": "1.0"
  },

2) after that, the pod function needs a ton of work to emit something that makes sense and have an index option.

Thanks, James.

**Comment by jhthorsen** [comment]
There's too much information inside your head that is not written down in this issue.

1) What are you trying to do?
2) What happens?
3) What is the expected result?

Please provide more information.

Also note that I'm going to replace Swagger2 with Mojolicious::Plugin::OpenAPI. And I will not have time to maintain both projects.

**Comment by jamesbriggs** [comment]
You're missing a bunch of common swagger properties. just diff against your petstore spec.

**Comment by jhthorsen** [comment]
Closing this issue, since there is not enough information for me to work with.

@mrenvoize: Please re-open if you understand what @jamesbriggs is trying to accomplish.

**Comment by mrenvoize** [comment]
I'm afraid I am completely lost by this comment too..
