### ISSUE TITLE
URL with userinfo doesn't work with Mojolicious 7 + Swagger2::Client->generate

### ISSUE THREAD

**Issue by le-garff-yoann** [jhthorsen/swagger2#96]
Hello,

Following this [modification](https://metacpan.org/pod/Mojo::URL#to_string) (which is coming with the version 7 of Mojolicious), the `generate` method no longer work with a URL + userinfo (on the other hand, the generated methods work on an endpoint with basicauth if i use `generate` with a locally stored spec file).

Do you have a solution for this ?

Thanks.

**Comment by jhthorsen** [comment]
Are you talking about "generate" in Swagger2::Client?

**Comment by le-garff-yoann** [comment]
Yes.

**Comment by jhthorsen** [comment]
I will no longer maintain this project.
