### ISSUE TITLE
How to describe an enumerated field?

### ISSUE THREAD

**Issue by AnotherOneAckap** [jhthorsen/swagger2#97]
Here is a short code made from http://json-schema.org/example2.html
Looks like it does not print possible values for enum field.
```
use Swagger2;
my $swagger = Swagger2->new;
local $/;
$swagger->parse(<DATA>);
print $swagger->pod->to_string;
__DATA__
swagger: 2.0
info:
  title: "Enum example"
  version: 0.1
host: "example.com"
basePath: "api"
paths:
  "/item":
    get:
      operationId: getItem
      description: "Returns Item"
      produces: [
        "application/json"
      ]$
      responses:
        '200':
          description: "Item"
          schema:
            type: object
            "$ref": "#/definitions/Item"
definitions:
  Item:
    type: object
    properties:
      fstype:
        enum: [ "ext3", "ext4", "btrfs" ]
```

**Comment by jhthorsen** [comment]
Can you explain what you mean about "does not print"?

Also note that this whole project is replaced by https://metacpan.org/release/Mojolicious-Plugin-OpenAPI

**Comment by AnotherOneAckap** [comment]
I mean it produced POD in which we can see:
```
Item

  {
    "fstype": enum, // No description.
  },
```
without possible values for this field, which are [ "ext3", "ext4", "btrfs" ]

**Comment by jhthorsen** [comment]
Thanks for the answer.

I'm sorry to say that I'm not going to maintain the POD renderer. If anyone wants to take over, then that is fine. IN M::P::OpenAPI, I'm rendering plain HTML instead. Here are some links:

* Example DOC: http://beta.convos.by/api.html
* M::P::OpenAPI tutorial: https://metacpan.org/pod/distribution/Mojolicious-Plugin-OpenAPI/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod
