### ISSUE TITLE
Undeclared dependency on JSON::Validator::OpenAPI::Mojolicious

### ISSUE THREAD

**Issue by andk** [jhthorsen/swagger2#98]
As per subject. Grep:

http://search.cpan.org/grep?release=Swagger2-0.87;string=JSON::Validator::OpenAPI::Mojolicious;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/75940047

HTH&&Thanks,

**Comment by jhthorsen** [comment]
Thanks for reporting in 👍 

This is fixed in version 0.88, which is on its way to CPAN.

https://github.com/jhthorsen/swagger2/commit/c15121f2f77632cf902a6161951a5a99d5cd5646
