### ISSUE TITLE
Tests fail (with JSON::Validator 0.94?)

### ISSUE THREAD

**Issue by eserte** [jhthorsen/swagger2#99]
On my smokers I see the following failure:
```
Mojo::Util::slurp is DEPRECATED in favor of Mojo::File::slurp at /home/cpansand/.cpan/build/2017022521/Mojolicious-7.26-xQN_XA/blib/lib/Mojo/Server.pm line 17.
Can't use string ("{
  "swagger": "2.0",
  "info": "...) as a SCALAR ref while "strict refs" in use at /home/cpansand/.cpan/build/2017022521/JSON-Validator-0.94-kFaAfU/blib/lib/JSON/Validator.pm line 165.
t/editor.t ............................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
... (etc.) ...
```

This seems to happen with the latest JSON::Validator release (0.94). See http://analysis.cpantesters.org/solved?distv=Swagger2-0.89#mod%3AJSON%3A%3AValidator for statistical analysis.

**Comment by kostya-ten** [comment]
Mojo::Util::slurp is DEPRECATED in favor of Mojo::File::slurp at /home/kostya/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/Mojo/Util.pm line 265.
	Mojo::Util::slurp("t/data/petstore.json") called at t/parse-json.t line 12
Can't use string ("{
  "swagger": "2.0",
  "info": "...) as a SCALAR ref while "strict refs" in use at /home/kostya/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/JSON/Validator.pm line 165.
t/parse-json.t ........................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Mojolicious::Plugin::Swagger2 is deprecated in favor of Mojolicious::Plugin::OpenAPI at (eval 91) line 1.
t/plugin-defaults.t ................... ok
Mojolicious::Plugin::Swagger2 is deprecated in favor of Mojolicious::Plugin::OpenAPI at (eval 91) line 1.
t/plugin-json.t ....................... ok
t/plugin-yaml.t ....................... skipped: Fails with JSON::Validator 0.91
Mojolicious::Plugin::Swagger2 is deprecated in favor of Mojolicious::Plugin::OpenAPI at (eval 91) line 1.
t/plugin.t ............................ ok
Mojo::Util::slurp is DEPRECATED in favor of Mojo::File::slurp at /home/kostya/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/Mojo/Util.pm line 265.
	Mojo::Util::slurp("t/data/pod-as-string.pod") called at t/pod-as-string.t line 10
t/pod-as-string.t ..................... ok
Mojolicious::Plugin::Swagger2 is deprecated i

**Comment by kostya-ten** [comment]
See Mojolicious::Plugin::OpenAPI

**Comment by jhthorsen** [comment]
Thanks for reporting in.

I'm considering if I should remove the plugin or fix the bug. Will hopefully come to a conclusion soon.

**Comment by mrenvoize** [comment]
I know of at least 1 project still using the Swagger plugin, but they're also pinned to an older Mojolicious and are in the process of migrating to OpenAPI too.

We did agree on a date for the removal of the plugin I believe..  just checking my notes now.

**Comment by mrenvoize** [comment]
```
2016-12-22 10:15:12] <ashimema_> When did you put the warning on cpan batman?
[2016-12-22 10:15:25] <batman> in the docs?
[2016-12-22 10:15:48] <batman> https://github.com/jhthorsen/swagger2/commit/50d95217333f35dfee12b1354a168689d86b78f3
[2016-12-22 10:16:08] <ashimema_> perhaps 12 months from that being added should be your kill switch for removing from cpan.. an enforced move to OpenAPI (I'd welcome it as it gives me more strength to argue about making the switch)
```

**Comment by mrenvoize** [comment]
So.. 6 months from announcing deprecation in the docs would put us at mid March, which we're really not far off now.

I don't know if anyone is using the bits of Swagger 2 which aren't replicated in OpenAPI..?

Swagger2::Client ?
Swagger2::Editor ? (I think this can go regardless, there's good editors out there already)
Mojolicious::Command::swagger2 ? (Just an interface to ::Client above, right?)

Hmm.. my feeling is replace the module with a simple POD with just the deprecation notice that points to OpenAPI as the replacement.

**Comment by jhthorsen** [comment]
I could remove all the tests and write a warning like "not maintained anymore".

**Comment by jhthorsen** [comment]
All tests have been removed in 5423999544193224c61ce54fbcf6575dd39d83dc. Closing this.
